name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
   build:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v5
         - uses: julia-actions/setup-julia@latest
           with:
             version: '1.11'
         - run: |
             julia --project=docs -e '
               using Pkg
               Pkg.develop(PackageSpec(path=pwd()))
               Pkg.instantiate()'
         - run: |
             julia --project=docs -e '
               using Documenter: doctest
               using Robustbase     
               doctest(Robustbase)' 
         - run: julia --project=docs docs/make.jl
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
         - uses: julia-actions/julia-processcoverage@latest
         - uses: codecov/codecov-action@v5
         